name: dimdom
description: Find everything around you
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.1.0
  auto_size_text: ^3.0.0
  camera: ^0.10.5+3
  cupertino_icons: ^1.0.5
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  file_picker: ^6.0.0
  flutter_avif: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_local_notifications: ^16.1.0
  flutter_map: ^6.0.1
  flutter_screenutil: ^5.8.4
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.8
  geolocator: ^10.1.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.2
  latlong2: ^0.9.0
  path: ^1.8.3
  path_provider: ^2.1.0
  photo_view: ^0.14.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  sqflite_sqlcipher: ^2.2.0
  url_launcher: ^6.2.1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

# change launcher icon, best
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/img/launcher.png"